<?php
    /**
     *
     * @package scf-framework
     * @author Steve
     * @date 11/19/13
     * @version 5.2
     */
    //add_action( 'admin_init', 'wfc_test_smtp' );
    class wfc_email
    {

        protected $WFC_SMTP_DEBUG = 2;
        protected $WFC_SMTP_DEBUGOUTPUT = 'html';
        protected $FROM_NAME = 'forms';
        protected $ADD_EMAIL = 'steve.fischer@webfullcircle.com';
        protected $smtp_settings;

        function __construct( $phpmailer ){
            $this->wfc_get_smtp_settings();
            $phpmailer->Mailer     = "smtp";
            $phpmailer->SMTPSecure = $this->smtp_settings['wfc_smtp_smtpsecure'];
            $phpmailer->Host       = $this->smtp_settings['wfc_smtp_smtpsecure'];
            $phpmailer->Port       = $this->smtp_settings['wfc_smtp_smtpsecure'];
            $phpmailer->SMTPAuth   = TRUE;
            $phpmailer->Username   = $this->smtp_settings['wfc_smtp_smtpsecure'];
            $phpmailer->Password   = $this->smtp_settings['wfc_smtp_smtpsecure'];
            $phpmailer             = apply_filters( 'wp_mail_smtp_custom_options', $phpmailer );
            add_filter( 'wp_mail_from', array($this, 'wfc_smtp_mail_from') );
            add_filter( 'wp_mail_from_name', array($this, 'wfc_smtp_mail_from_name') );
        }

        protected function wfc_set_phpmailer(){
        }

        private function wfc_get_smtp_settings(){
            $array               = array(
                'wfc_smtp_host'       => get_option( 'wfc_mail_smtp_host' ),
                'wfc_smtp_port'       => get_option( 'wfc_mail_smtp_port' ),
                'wfc_smtp_smtpsecure' => get_option( 'wfc_mail_smtp_smtpsecure' ),
                'wfc_smtp_smtpauth'   => get_option( 'wfc_mail_smtp_smtpauth' ),
                'wfc_smtp_user'       => get_option( 'wfc_mail_smtp_user' ),
                'wfc_smtp_pass'       => get_option( 'wfc_mail_smtp_pass' )
            );
            $this->smtp_settings = $array;
        }

        function wfc_smtp_mail_from( $orig ){
            $sitename = strtolower( $_SERVER['SERVER_NAME'] );
            if( substr( $sitename, 0, 4 ) == 'www.' ){
                $sitename = substr( $sitename, 4 );
            }
            $default_from = 'wordpress@'.$sitename;
            if( $orig != $default_from ){
                return $orig;
            }
            return get_option( 'wfc_mail_from_email' );
        }

        function wfc_smtp_mail_from_name( $orig ){
            if( $orig == 'WordPress' ){
                return get_option( 'wfc_mail_from_name' );
            }
            return $orig;
        }

        /*
    * @sftodo: this needs to be finished
    */
        function wfc_test_smtp(){
            global $phpmailer;
            if( !is_object( $phpmailer ) || !is_a( $phpmailer, 'PHPMailer' ) ){
                require_once ABSPATH.WPINC.'/class-phpmailer.php';
                require_once ABSPATH.WPINC.'/class-smtp.php';
                $phpmailer = new PHPMailer();
            }
            // Send a test mail if necessary
            if( isset($_POST['wpms_action']) && $_POST['wpms_action'] == __( 'Send Test', 'wp_mail_smtp' ) && isset($_POST['to']) ){
                // Set up the mail variables
                $to      = $_POST['to'];
                $subject = 'WP Mail SMTP: '.__( 'Test mail to ', 'wp_mail_smtp' ).$to;
                $message = __( 'This is a test email generated by the WP Mail SMTP WordPress plugin.', 'wp_mail_smtp' );
                // Set SMTPDebug to level 2
                $phpmailer->SMTPDebug = 2;
                // Start output buffering to grab smtp debugging output
                ob_start();
                // Send the test mail
                $result = wp_mail( $to, $subject, $message );
                // Strip out the language strings which confuse users
                //unset($phpmailer->language);
                // This property became protected in WP 3.2
                // Grab the smtp debugging output
                $smtp_debug = ob_get_clean();

                // Output the response
                ?>
                <div id="message" class="updated fade"><p><strong><?php _e( 'Test Message Sent', 'wp_mail_smtp' ); ?></strong></p>
                    <p><?php _e( 'The result was:', 'wp_mail_smtp' ); ?></p>
                    <pre><?php var_dump( $result ); ?></pre>
                    <p><?php _e( 'The full debugging output is shown below:', 'wp_mail_smtp' ); ?></p>
                    <pre><?php var_dump( $phpmailer ); ?></pre>
                    <p><?php _e( 'The SMTP debugging output is shown below:', 'wp_mail_smtp' ); ?></p>
                    <pre><?php echo $smtp_debug ?></pre>
                </div>
                <?php

                // Destroy $phpmailer so it doesn't cause issues later
                unset($phpmailer);
            }
        }
    }