<?php
    /**
     *
     * @package scf-framework
     * @author Steve
     * @date 11/19/13
     * @version 5.2
     */
    add_action( 'phpmailer_init', 'wfc_phpmailer' );
    //add_action( 'admin_init', 'wfc_test_smtp' );
    define('WFC_SMTP_DEBUG', 2);
    define('WFC_SMTP_DEBUGOUTPUT', 'html');
    define('WFC_SMTP_HOST', 'smtpcorp.com');
    define('WFC_SMTP_PORT', 465);
    define('WFC_SMTP_SMTPSECURE', 'ssl');
    define('WFC_SMTP_SMTPAUTH', true);
    define('WFC_SMTP_USER', "steve.fischer@webfullcircle.com");
    define('WFC_SMTP_PASS', "K5GNJy6r");
    define('FROM_NAME', 'forms');
    define('ADD_EMAIL', 'steve.fischer@webfullcircle.com');
    define('BODY', "email came from".$_SERVER['HTTP_HOST']);
    //wordpress default from is wordpress@sitename and from name is WordPress
    add_filter( 'wp_mail_from', 'wfc_smtp_mail_from' );
    add_filter( 'wp_mail_from_name', 'wfc_smtp_mail_from_name' );
    function wfc_smtp_mail_from( $orig ){
        $sitename = strtolower( $_SERVER['SERVER_NAME'] );
        if( substr( $sitename, 0, 4 ) == 'www.' ){
            $sitename = substr( $sitename, 4 );
        }
        $default_from = 'wordpress@'.$sitename;
        if( $orig != $default_from ){
            return $orig;
        }
        return get_option( 'wfc_mail_from_email' );
    }

    function wfc_smtp_mail_from_name( $orig ){
        if( $orig == 'WordPress' ){
            return get_option( 'wfc_mail_from_name' );
        }
        return $orig;
    }

    /*
     * @sftodo: this needs to be finished
     */
    function wfc_test_smtp(){
        global $phpmailer;

        if ( !is_object( $phpmailer ) || !is_a( $phpmailer, 'PHPMailer' ) ) {
            require_once ABSPATH . WPINC . '/class-phpmailer.php';
            require_once ABSPATH . WPINC . '/class-smtp.php';
            $phpmailer = new PHPMailer();
        }

        // Send a test mail if necessary
        if (isset($_POST['wpms_action']) && $_POST['wpms_action'] == __('Send Test', 'wp_mail_smtp') && isset($_POST['to'])) {

            // Set up the mail variables
            $to = $_POST['to'];
            $subject = 'WP Mail SMTP: ' . __('Test mail to ', 'wp_mail_smtp') . $to;
            $message = __('This is a test email generated by the WP Mail SMTP WordPress plugin.', 'wp_mail_smtp');

            // Set SMTPDebug to level 2
            $phpmailer->SMTPDebug = 2;

            // Start output buffering to grab smtp debugging output
            ob_start();

            // Send the test mail
            $result = wp_mail($to,$subject,$message);

            // Strip out the language strings which confuse users
            //unset($phpmailer->language);
            // This property became protected in WP 3.2

            // Grab the smtp debugging output
            $smtp_debug = ob_get_clean();

            // Output the response
            ?>
            <div id="message" class="updated fade"><p><strong><?php _e('Test Message Sent', 'wp_mail_smtp'); ?></strong></p>
                <p><?php _e('The result was:', 'wp_mail_smtp'); ?></p>
                <pre><?php var_dump($result); ?></pre>
                <p><?php _e('The full debugging output is shown below:', 'wp_mail_smtp'); ?></p>
                <pre><?php var_dump($phpmailer); ?></pre>
                <p><?php _e('The SMTP debugging output is shown below:', 'wp_mail_smtp'); ?></p>
                <pre><?php echo $smtp_debug ?></pre>
            </div>
            <?php

            // Destroy $phpmailer so it doesn't cause issues later
            unset($phpmailer);

        }
    }

    if( !function_exists( 'wfc_phpmailer' ) ) :
        function wfc_phpmailer( $phpmailer ){
            $phpmailer->Mailer     = "smtp";
            $phpmailer->SMTPSecure = WFC_SMTP_SMTPSECURE;
            $phpmailer->Host       = WFC_SMTP_HOST;
            $phpmailer->Port       = WFC_SMTP_PORT;
            $phpmailer->SMTPAuth   = TRUE;
            $phpmailer->Username   = WFC_SMTP_USER;
            $phpmailer->Password   = WFC_SMTP_PASS;
            $phpmailer             = apply_filters( 'wp_mail_smtp_custom_options', $phpmailer );
        }
    endif;
